require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'config/environments/*'
    - 'node_modules/**/*'
    - 'bin/**/*'
    - 'coverage/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'spec/*_helper.rb'
    - 'Gemfile'
