version: '3'

services:
  web:
    build: .
    command: bash -c "bundle check || bundle install && rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    links:
      - postgres
    ports:
      - 3000:3000
    expose:
      - 3000

  webpacker:
    build: .
    env_file:
      - .env
    command: bash -c "yarn install && bin/webpack-dev-server"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    ports:
      - 3035:3035

  postgres:
    image: postgres:10.4
    env_file:
      - .env
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432

volumes:
  gem_cache:
  node_modules:
  postgresql_data:
